services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    expose:
      - "3000"

  caddy:
    image: caddy:2.8-alpine
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN=${DOMAIN}
      - CADDY_ADMIN_EMAIL=${CADDY_ADMIN_EMAIL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
